version: '3'
services:
  etl:
    build: .
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres:11
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    volumes:
      - ./SQL/PostgresTables.sql:/docker-entrypoint-initdb.d/PostgresTables.sql